
syntax keyword cmakeStatement target_include_directories set_property add_compile_options target_compile_definitions ExternalProject_Add target_compile_options

syntax keyword Keyword PUBLIC PRIVATE
